"""
models.py — All request/response models for MoneyLogix Strategy Builder.
These are the contracts between frontend and backend. Do not change field
names without updating the frontend TypeScript types simultaneously.
"""
from pydantic import BaseModel, Field
from enum import Enum
from typing import Optional, List, Dict

# --- Enums ---

class OptionType(str, Enum):
    CALL = "call"
    PUT = "put"

class Side(str, Enum):
    BUY = "buy"
    SELL = "sell"

class StrategyType(str, Enum):
    IRON_CONDOR = "iron_condor"
    LONG_STRADDLE = "long_straddle"
    LONG_STRANGLE = "long_strangle"
    BULL_CALL_SPREAD = "bull_call_spread"
    BULL_PUT_SPREAD = "bull_put_spread"
    BEAR_PUT_SPREAD = "bear_put_spread"
    COVERED_CALL = "covered_call"
    CUSTOM = "custom"

class DataModeType(str, Enum):
    LIVE = "live"
    CACHED = "cached"
    SNAPSHOT = "snapshot"
    DEMO = "demo"

# --- Core domain models ---

class Leg(BaseModel):
    id: str                        # UUID string, generated by frontend
    symbol: str = "NIFTY"
    strike: float
    expiry: str                    # ISO date: "2024-07-25"
    option_type: OptionType
    side: Side
    quantity: int = Field(ge=1, le=50)
    lot_size: int = Field(ge=1)    # 50 for Nifty, 15 for BankNifty
    iv: float = Field(ge=0)        # implied volatility as decimal (0.15 = 15%)

class Greeks(BaseModel):
    delta: float
    gamma: float
    theta: float                   # per calendar day
    vega: float                    # per 1% IV move
    price: float                   # option premium
    pop: float                     # probability of profit (0-1)

class LegGreekContribution(BaseModel):
    leg_id: str
    delta: float
    gamma: float
    theta: float
    vega: float

class PortfolioGreeks(BaseModel):
    net_delta: float
    net_gamma: float
    net_theta: float               # total daily theta P&L
    net_vega: float
    leg_contributions: List[LegGreekContribution]

class RiskMetrics(BaseModel):
    max_profit: float              # 999999999.0 means unlimited
    max_loss: float                # -999999999.0 means unlimited loss
    breakevens: List[float]
    probability_of_profit: float   # 0-1
    margin_required: float

class LiquidityInfo(BaseModel):
    score: float                   # 0-100
    label: str                     # "Good" | "Moderate" | "Poor..."
    spread_pct: float

class PayoffPoint(BaseModel):
    price: float
    pnl: float

class StrategyMetrics(BaseModel):
    legs: List[Leg]
    greeks_per_leg: List[Greeks]
    portfolio_greeks: PortfolioGreeks
    risk_metrics: RiskMetrics
    liquidity: LiquidityInfo
    payoff_curve: List[PayoffPoint]
    iv_rank: float = 0.0
    expected_move_pct: float = 0.0

class AssumptionCheck(BaseModel):
    name: str
    status: str                    # "valid" | "broken" | "warning"
    reason: str                    # Must contain specific numbers, not vague text
    icon: str                      # "✅" | "❌" | "⚠️"

class AssumptionResult(BaseModel):
    checks: List[AssumptionCheck]
    valid_count: int
    total_count: int
    score_display: str             # "3/4" or "N/A" for custom

class StressTestResult(BaseModel):
    matrix: List[List[float]]      # 5 rows (IV shocks) × 7 cols (price shocks)
    price_shocks: List[str]        # ["-5%", "-3%", "-1%", "0%", "+1%", "+3%", "+5%"]
    iv_shocks: List[str]           # ["-30pp", "-15pp", "0", "+15pp", "+30pp"]
    max_loss_scenario: float
    max_gain_scenario: float
    current_pnl: float             # center cell, should be ≈ 0

class HealthDiff(BaseModel):
    iv: Optional[Dict] = None      # {from, to, change, label, direction}
    price: Optional[Dict] = None   # {from, to, pct, label}
    pnl: Optional[Dict] = None     # {from, to, change, label}
    delta: Optional[Dict] = None   # {from, to, change, label}
    has_changes: bool = False
    dte_warning: bool = False

class DataMode(BaseModel):
    mode: DataModeType
    timestamp: Optional[str] = None  # ISO string, set when mode is "cached"

# --- Request / Response models ---

class AnalyzeRequest(BaseModel):
    legs: List[Leg]
    strategy_type: StrategyType = StrategyType.CUSTOM
    symbol: str = "NIFTY"

class AnalyzeResponse(BaseModel):
    metrics: StrategyMetrics
    assumptions: AssumptionResult
    data_mode: DataMode

class SaveStrategyRequest(BaseModel):
    strategy_id: str
    legs: List[Leg]
    metrics: StrategyMetrics
    symbol: str
    strategy_type: StrategyType

class AdjustmentSimulateRequest(BaseModel):
    original_legs: List[Leg]
    adjusted_legs: List[Leg]
    symbol: str = "NIFTY"

class AdjustmentComparison(BaseModel):
    delta_max_profit: float
    delta_max_loss: float
    delta_margin: float
    delta_net_theta: float
    max_profit_changed_by: str     # "▲ ₹1,200 (+18%)"
    max_loss_changed_by: str
    margin_changed_by: str
    summary: str                   # factual 1-sentence, never directive

class AdjustmentSimulateResponse(BaseModel):
    original: StrategyMetrics
    adjusted: StrategyMetrics
    comparison: AdjustmentComparison
    data_mode: DataMode

class CopilotHintRequest(BaseModel):
    changed_leg_before: Leg
    changed_leg_after: Leg
    metrics_before: StrategyMetrics
    metrics_after: StrategyMetrics

class HealthEvent(BaseModel):
    diff: HealthDiff
    explanation: str
    data_mode: str
    checked_at: str                # ISO timestamp